// Généré automatiquement depuis trainyard_standard_levels.csv (extraction officielle
// trainyard.ca, catalogues Regular/Bonus/Express, 233 niveaux, 36 familles).
// Catalogue compact : chaque niveau ne porte que son puzzleString + métadonnées,
// jamais les objets décodés (voir hydrateLevel() dans hydrate.ts, appelé à la
// demande lorsqu'un niveau devient actif).
// Ne pas éditer à la main : régénérer via scripts/generateStandardCatalog.ts.
import type { LevelFamily } from "./types";

export const STANDARD_FAMILIES: LevelFamily[] = [
  {
    id: "regular-abbotsford",
    title: "Abbotsford",
    playable: true,
    levels: [
      {
        id: "std-redLine",
        title: "Red Line",
        number: 1,
        brief: "",
        family: "regular-abbotsford",
        width: 7,
        height: 7,
        railLimit: 6,
        optimalRails: 3,
        optimalCells: 3,
        optimalSwitchCells: 0,
        wrenches: 1,
        puzzleString: "hh002Oja3Giaa00"
      },
      {
        id: "std-grorangeLines",
        title: "Grorange lines",
        number: 2,
        brief: "",
        family: "regular-abbotsford",
        width: 7,
        height: 7,
        railLimit: 10,
        optimalRails: 5,
        optimalCells: 5,
        optimalSwitchCells: 0,
        wrenches: 1,
        puzzleString: "hh8OsC007GbaCOjv2Giav"
      },
      {
        id: "std-yorpleLines",
        title: "Yorple lines",
        number: 3,
        brief: "",
        family: "regular-abbotsford",
        width: 7,
        height: 7,
        railLimit: 24,
        optimalRails: 12,
        optimalCells: 12,
        optimalSwitchCells: 0,
        wrenches: 1,
        puzzleString: "hhGcaJ5OBJ8Osh3Geah9Gbah3Oah8OjJ5GiaJ"
      },
      {
        id: "std-magicalTrains",
        title: "Magical Trains",
        number: 4,
        brief: "",
        family: "regular-abbotsford",
        width: 7,
        height: 7,
        railLimit: 20,
        optimalRails: 10,
        optimalCells: 9,
        optimalSwitchCells: 1,
        wrenches: 1,
        puzzleString: "hh3GeaJ07OjJ5GiaJ07OaJ"
      },
      {
        id: "std-theRedCorner",
        title: "The Red Corner",
        number: 5,
        brief: "",
        family: "regular-abbotsford",
        width: 7,
        height: 7,
        railLimit: 14,
        optimalRails: 7,
        optimalCells: 7,
        optimalSwitchCells: 0,
        wrenches: 1,
        puzzleString: "hh8Osa0001Giaa"
      },
      {
        id: "std-purpablu",
        title: "Purpablu",
        number: 6,
        brief: "",
        family: "regular-abbotsford",
        width: 7,
        height: 7,
        railLimit: 32,
        optimalRails: 16,
        optimalCells: 16,
        optimalSwitchCells: 0,
        wrenches: 1,
        puzzleString: "hh8OBJ3GcaJ003Oso3Gbao"
      }
    ]
  },
  {
    id: "regular-brampton",
    title: "Brampton",
    playable: true,
    levels: [
      {
        id: "std-aRockInTheWay",
        title: "A Rock in the Way",
        number: 1,
        brief: "",
        family: "regular-brampton",
        width: 7,
        height: 7,
        railLimit: 14,
        optimalRails: 7,
        optimalCells: 7,
        optimalSwitchCells: 0,
        wrenches: 1,
        puzzleString: "hh3GeaC00R00OaC"
      },
      {
        id: "std-greenWally",
        title: "Green Wally",
        number: 2,
        brief: "",
        family: "regular-brampton",
        width: 7,
        height: 7,
        railLimit: 18,
        optimalRails: 9,
        optimalCells: 9,
        optimalSwitchCells: 0,
        wrenches: 1,
        puzzleString: "hh8GeaC1R1OsC4R6R6R6R6R"
      },
      {
        id: "std-yellowSnake",
        title: "Yellow Snake",
        number: 3,
        brief: "",
        family: "regular-brampton",
        width: 7,
        height: 7,
        railLimit: 46,
        optimalRails: 23,
        optimalCells: 23,
        optimalSwitchCells: 0,
        wrenches: 1,
        puzzleString: "hh6OBh1RRRRRR7RRRRRR05Gcah"
      },
      {
        id: "std-uTurn",
        title: "U-Turn",
        number: 4,
        brief: "",
        family: "regular-brampton",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 26,
        optimalCells: 24,
        optimalSwitchCells: 2,
        wrenches: 1,
        puzzleString: "hhOsJRGeaJ1GeaaROsa1R3R2R3R2R3R2R3R2R3R"
      },
      {
        id: "std-journey",
        title: "Journey",
        number: 5,
        brief: "",
        family: "regular-brampton",
        width: 7,
        height: 7,
        railLimit: 22,
        optimalRails: 11,
        optimalCells: 11,
        optimalSwitchCells: 0,
        wrenches: 1,
        puzzleString: "hhR5Geav3R4R9R8R2R4Oav4R"
      }
    ]
  },
  {
    id: "regular-calgary",
    title: "Calgary",
    playable: true,
    levels: [
      {
        id: "std-rainbow",
        title: "Rainbow",
        number: 1,
        brief: "",
        family: "regular-calgary",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 40,
        optimalCells: 25,
        optimalSwitchCells: 15,
        wrenches: 1,
        puzzleString: "hhGeaaOsJGeaoOsCGeahOsvGeaa0005OaaGbaJOaoGbaCOahGbavOaa"
      },
      {
        id: "std-innieOutie",
        title: "Innie Outie",
        number: 2,
        brief: "",
        family: "regular-calgary",
        width: 7,
        height: 7,
        railLimit: 26,
        optimalRails: 13,
        optimalCells: 11,
        optimalSwitchCells: 2,
        wrenches: 1,
        puzzleString: "hh02Oja5Ojo01Giao5Giaa0"
      },
      {
        id: "std-aroundTheBack",
        title: "Around the Back",
        number: 3,
        brief: "",
        family: "regular-calgary",
        width: 7,
        height: 7,
        railLimit: 30,
        optimalRails: 15,
        optimalCells: 11,
        optimalSwitchCells: 4,
        wrenches: 2,
        puzzleString: "hh8Oja3Giao9Ojh3Giaa9Ojo3Giah"
      },
      {
        id: "std-multiColor",
        title: "Multicolor",
        number: 4,
        brief: "",
        family: "regular-calgary",
        width: 7,
        height: 7,
        railLimit: 16,
        optimalRails: 8,
        optimalCells: 8,
        optimalSwitchCells: 0,
        wrenches: 1,
        puzzleString: "hh3Oso07OjC2GpdEb2OBh07Oaa"
      },
      {
        id: "std-squiggle",
        title: "Squiggle",
        number: 5,
        brief: "",
        family: "regular-calgary",
        width: 7,
        height: 7,
        railLimit: 16,
        optimalRails: 8,
        optimalCells: 8,
        optimalSwitchCells: 0,
        wrenches: 1,
        puzzleString: "hh07Oav6GkbF6OsC0"
      },
      {
        id: "std-twoTwo",
        title: "Two Two",
        number: 6,
        brief: "",
        family: "regular-calgary",
        width: 7,
        height: 7,
        railLimit: 10,
        optimalRails: 5,
        optimalCells: 5,
        optimalSwitchCells: 0,
        wrenches: 1,
        puzzleString: "hh3Geba00001Oba"
      },
      {
        id: "std-crossover",
        title: "Crossover",
        number: 7,
        brief: "",
        family: "regular-calgary",
        width: 7,
        height: 7,
        railLimit: 24,
        optimalRails: 12,
        optimalCells: 10,
        optimalSwitchCells: 2,
        wrenches: 2,
        puzzleString: "hh3Oso07Oja5Giaa07Gbao"
      }
    ]
  },
  {
    id: "regular-delson",
    title: "Delson",
    playable: true,
    levels: [
      {
        id: "std-mellowYellow",
        title: "Mellow Yellow",
        number: 1,
        brief: "",
        family: "regular-delson",
        width: 7,
        height: 7,
        railLimit: 14,
        optimalRails: 7,
        optimalCells: 6,
        optimalSwitchCells: 1,
        wrenches: 2,
        puzzleString: "hh0Geah005Gcah3OCi"
      },
      {
        id: "std-deliveringOranges",
        title: "Delivering Oranges",
        number: 2,
        brief: "",
        family: "regular-delson",
        width: 7,
        height: 7,
        railLimit: 14,
        optimalRails: 7,
        optimalCells: 6,
        optimalSwitchCells: 1,
        wrenches: 2,
        puzzleString: "hh004Oby6Geav03Gbav"
      },
      {
        id: "std-purpleParcels",
        title: "Purple Parcels",
        number: 3,
        brief: "",
        family: "regular-delson",
        width: 7,
        height: 7,
        railLimit: 34,
        optimalRails: 17,
        optimalCells: 15,
        optimalSwitchCells: 2,
        wrenches: 2,
        puzzleString: "hhOuOJ5GmaJ3R01R1R1R01R3GdaJ5GjaJ"
      },
      {
        id: "std-prellow",
        title: "Prellow",
        number: 4,
        brief: "",
        family: "regular-delson",
        width: 7,
        height: 7,
        railLimit: 14,
        optimalRails: 7,
        optimalCells: 6,
        optimalSwitchCells: 1,
        wrenches: 2,
        puzzleString: "hh8GcaJ3Giah005ObK0"
      },
      {
        id: "std-aroundTheBend",
        title: "Around the Bend",
        number: 5,
        brief: "",
        family: "regular-delson",
        width: 7,
        height: 7,
        railLimit: 38,
        optimalRails: 19,
        optimalCells: 18,
        optimalSwitchCells: 1,
        wrenches: 2,
        puzzleString: "hh002RRRGeavObxGeao5R6R"
      },
      {
        id: "std-preenies",
        title: "Preenies",
        number: 6,
        brief: "",
        family: "regular-delson",
        width: 7,
        height: 7,
        railLimit: 48,
        optimalRails: 24,
        optimalCells: 23,
        optimalSwitchCells: 1,
        wrenches: 2,
        puzzleString: "hhOrNNNNJ6RRRRRR9RRRRRR3R6R3GddGG5GjeOOJ"
      },
      {
        id: "std-tooMany",
        title: "Too Many",
        number: 7,
        brief: "",
        family: "regular-delson",
        width: 7,
        height: 7,
        railLimit: 34,
        optimalRails: 17,
        optimalCells: 15,
        optimalSwitchCells: 2,
        wrenches: 3,
        puzzleString: "hh3GelGGqqyy0RRR1RRRRRR1RRR8OEGG1Odqq1Omyy"
      }
    ]
  },
  {
    id: "regular-edmonton",
    title: "Edmonton",
    playable: true,
    levels: [
      {
        id: "std-yield",
        title: "Yield",
        number: 1,
        brief: "",
        family: "regular-edmonton",
        width: 7,
        height: 7,
        railLimit: 16,
        optimalRails: 8,
        optimalCells: 7,
        optimalSwitchCells: 1,
        wrenches: 3,
        puzzleString: "hh8Ojh07Giah9Ojh0"
      },
      {
        id: "std-blueBoys",
        title: "Blue Boys",
        number: 2,
        brief: "",
        family: "regular-edmonton",
        width: 7,
        height: 7,
        railLimit: 10,
        optimalRails: 5,
        optimalCells: 4,
        optimalSwitchCells: 1,
        wrenches: 3,
        puzzleString: "hh0Oso05OBo01Gbao0"
      },
      {
        id: "std-timingTest",
        title: "Timing Test",
        number: 3,
        brief: "",
        family: "regular-edmonton",
        width: 7,
        height: 7,
        railLimit: 30,
        optimalRails: 15,
        optimalCells: 12,
        optimalSwitchCells: 3,
        wrenches: 3,
        puzzleString: "hh8Oja3Oja0002Giaa"
      },
      {
        id: "std-grimaceTown",
        title: "Grimace Town",
        number: 4,
        brief: "",
        family: "regular-edmonton",
        width: 7,
        height: 7,
        railLimit: 24,
        optimalRails: 12,
        optimalCells: 10,
        optimalSwitchCells: 2,
        wrenches: 3,
        puzzleString: "hh3GeaJ07GcaJ5GiaJ07OcOJ"
      },
      {
        id: "std-lemonLatency",
        title: "Lemon Latency",
        number: 5,
        brief: "",
        family: "regular-edmonton",
        width: 7,
        height: 7,
        railLimit: 28,
        optimalRails: 14,
        optimalCells: 11,
        optimalSwitchCells: 3,
        wrenches: 3,
        puzzleString: "hhGeahOsh00005OBh"
      },
      {
        id: "std-threeReds",
        title: "Three Reds",
        number: 6,
        brief: "",
        family: "regular-edmonton",
        width: 7,
        height: 7,
        railLimit: 32,
        optimalRails: 16,
        optimalCells: 12,
        optimalSwitchCells: 4,
        wrenches: 3,
        puzzleString: "hhOsa1Osa3Osa0008Gbaa"
      },
      {
        id: "std-colourTheory",
        title: "Colour Theory",
        number: 7,
        brief: "",
        family: "regular-edmonton",
        width: 7,
        height: 7,
        railLimit: 12,
        optimalRails: 6,
        optimalCells: 5,
        optimalSwitchCells: 1,
        wrenches: 3,
        puzzleString: "hh05Ojo3OBh08GbaC0"
      },
      {
        id: "std-secondary",
        title: "Secondary",
        number: 8,
        brief: "",
        family: "regular-edmonton",
        width: 7,
        height: 7,
        railLimit: 30,
        optimalRails: 15,
        optimalCells: 12,
        optimalSwitchCells: 3,
        wrenches: 3,
        puzzleString: "hhOsa5Osh00001Gbav"
      },
      {
        id: "std-nurple",
        title: "Nurple",
        number: 9,
        brief: "",
        family: "regular-edmonton",
        width: 7,
        height: 7,
        railLimit: 18,
        optimalRails: 9,
        optimalCells: 8,
        optimalSwitchCells: 1,
        wrenches: 3,
        puzzleString: "hh8Osa05GpaJ05Oao"
      }
    ]
  },
  {
    id: "regular-fredericton",
    title: "Fredericton",
    playable: true,
    levels: [
      {
        id: "std-microMix",
        title: "Micro Mix",
        number: 1,
        brief: "",
        family: "regular-fredericton",
        width: 7,
        height: 7,
        railLimit: 20,
        optimalRails: 10,
        optimalCells: 9,
        optimalSwitchCells: 1,
        wrenches: 3,
        puzzleString: "hh8Ojo007OBhGcaC0"
      },
      {
        id: "std-theFirst",
        title: "The First",
        number: 2,
        brief: "",
        family: "regular-fredericton",
        width: 7,
        height: 7,
        railLimit: 18,
        optimalRails: 9,
        optimalCells: 7,
        optimalSwitchCells: 2,
        wrenches: 3,
        puzzleString: "hh0Oso01GcaJ3GiaJ01Oaa0"
      },
      {
        id: "std-waitOutside",
        title: "Wait Outside",
        number: 3,
        brief: "",
        family: "regular-fredericton",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 25,
        optimalCells: 24,
        optimalSwitchCells: 1,
        wrenches: 3,
        puzzleString: "hh8Osa1R1R4R1R1RRRR1R6R6R1GcaJ4ROao"
      },
      {
        id: "std-nineMensMorris",
        title: "Nine Men's Morris",
        number: 4,
        brief: "",
        family: "regular-fredericton",
        width: 7,
        height: 7,
        railLimit: 34,
        optimalRails: 17,
        optimalCells: 15,
        optimalSwitchCells: 2,
        wrenches: 3,
        puzzleString: "hhOsh5Gmav9RRR4RRR4RRR9Gdav5Oaa"
      },
      {
        id: "std-eeeTee",
        title: "Eee Tee",
        number: 5,
        brief: "",
        family: "regular-fredericton",
        width: 7,
        height: 7,
        railLimit: 36,
        optimalRails: 18,
        optimalCells: 15,
        optimalSwitchCells: 3,
        wrenches: 3,
        puzzleString: "hh009Oaa3Oah9OBa1GbbA1Ojo"
      },
      {
        id: "std-relish",
        title: "Relish",
        number: 6,
        brief: "",
        family: "regular-fredericton",
        width: 7,
        height: 7,
        railLimit: 44,
        optimalRails: 22,
        optimalCells: 16,
        optimalSwitchCells: 6,
        wrenches: 4,
        puzzleString: "hhROjh5OsCGeaC000RR5ROjo"
      }
    ]
  },
  {
    id: "regular-guelph",
    title: "Guelph",
    playable: true,
    levels: [
      {
        id: "std-mirrorSquad",
        title: "Mirror Squad",
        number: 1,
        brief: "",
        family: "regular-guelph",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 26,
        optimalCells: 20,
        optimalSwitchCells: 6,
        wrenches: 3,
        puzzleString: "hhOja8R3GiaJOjo1R4RRRRRRR4R1OBoGcaC3R8OBh"
      },
      {
        id: "std-cuteLoop",
        title: "Cute Loop",
        number: 2,
        brief: "",
        family: "regular-guelph",
        width: 7,
        height: 7,
        railLimit: 46,
        optimalRails: 23,
        optimalCells: 20,
        optimalSwitchCells: 3,
        wrenches: 3,
        puzzleString: "hhOja5OBoR1RRRRR4R1GiaJ4R6R6R"
      },
      {
        id: "std-hourglass",
        title: "Hourglass",
        number: 3,
        brief: "",
        family: "regular-guelph",
        width: 7,
        height: 7,
        railLimit: 48,
        optimalRails: 24,
        optimalCells: 18,
        optimalSwitchCells: 6,
        wrenches: 4,
        puzzleString: "hhOja5OBh0GbaJ6R6Geav0Oja5OBo"
      },
      {
        id: "std-gauss",
        title: "Gauss",
        number: 4,
        brief: "",
        family: "regular-guelph",
        width: 7,
        height: 7,
        railLimit: 28,
        optimalRails: 14,
        optimalCells: 10,
        optimalSwitchCells: 4,
        wrenches: 4,
        puzzleString: "hh04Oja5OBJR5ROjo5GiaJ0"
      },
      {
        id: "std-thirdWheel",
        title: "Third Wheel",
        number: 5,
        brief: "",
        family: "regular-guelph",
        width: 7,
        height: 7,
        railLimit: 36,
        optimalRails: 18,
        optimalCells: 14,
        optimalSwitchCells: 4,
        wrenches: 4,
        puzzleString: "hh3Osv07Oah5Oaa07Gbav"
      },
      {
        id: "std-turtles",
        title: "Turtles",
        number: 6,
        brief: "",
        family: "regular-guelph",
        width: 7,
        height: 7,
        railLimit: 48,
        optimalRails: 24,
        optimalCells: 20,
        optimalSwitchCells: 4,
        wrenches: 4,
        puzzleString: "hh02R6R6R1OjC3OBCR6R1OjC3OBCRGbaC"
      },
      {
        id: "std-royals",
        title: "Royals",
        number: 7,
        brief: "",
        family: "regular-guelph",
        width: 7,
        height: 7,
        railLimit: 46,
        optimalRails: 23,
        optimalCells: 20,
        optimalSwitchCells: 3,
        wrenches: 4,
        puzzleString: "hhOsJ007RRRRRR8GbaJROjJ"
      },
      {
        id: "std-spiced",
        title: "Spiced",
        number: 8,
        brief: "",
        family: "regular-guelph",
        width: 7,
        height: 7,
        railLimit: 40,
        optimalRails: 20,
        optimalCells: 17,
        optimalSwitchCells: 3,
        wrenches: 4,
        puzzleString: "hhOka5OCi07Gpby07Oki5OCa"
      }
    ]
  },
  {
    id: "regular-halifax",
    title: "Halifax",
    playable: true,
    levels: [
      {
        id: "std-handlebars",
        title: "Handlebars",
        number: 1,
        brief: "",
        family: "regular-halifax",
        width: 7,
        height: 7,
        railLimit: 44,
        optimalRails: 22,
        optimalCells: 18,
        optimalSwitchCells: 4,
        wrenches: 4,
        puzzleString: "hhGcaC5GiaCOso5Osh001Oah5OaoGcaC5GiaC"
      },
      {
        id: "std-compact",
        title: "Compact",
        number: 2,
        brief: "",
        family: "regular-halifax",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 25,
        optimalCells: 18,
        optimalSwitchCells: 7,
        wrenches: 4,
        puzzleString: "hh06GjavOaaR4OBoROja4ROshGgaJ0"
      },
      {
        id: "std-wailing",
        title: "Wailing",
        number: 3,
        brief: "",
        family: "regular-halifax",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 25,
        optimalCells: 21,
        optimalSwitchCells: 4,
        wrenches: 5,
        puzzleString: "hh3R4Ojo1R1Giaa4R4Oja3Giah4R4Ojh1R1Giao4R"
      },
      {
        id: "std-laserMaster",
        title: "Laser Master",
        number: 4,
        brief: "",
        family: "regular-halifax",
        width: 7,
        height: 7,
        railLimit: 24,
        optimalRails: 12,
        optimalCells: 8,
        optimalSwitchCells: 4,
        wrenches: 7,
        puzzleString: "hh3GedOO00001Odcc"
      },
      {
        id: "std-squads",
        title: "Squads",
        number: 5,
        brief: "",
        family: "regular-halifax",
        width: 7,
        height: 7,
        railLimit: 44,
        optimalRails: 22,
        optimalCells: 15,
        optimalSwitchCells: 7,
        wrenches: 6,
        puzzleString: "hh1Oja5Oso06GedOy06Oaa5OBh"
      },
      {
        id: "std-aspire",
        title: "Aspire",
        number: 6,
        brief: "",
        family: "regular-halifax",
        width: 7,
        height: 7,
        railLimit: 36,
        optimalRails: 18,
        optimalCells: 14,
        optimalSwitchCells: 4,
        wrenches: 7,
        puzzleString: "hh009GiaCOtoOtb4Giaa6R"
      },
      {
        id: "std-underTheFence",
        title: "Under The Fence",
        number: 7,
        brief: "",
        family: "regular-halifax",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 28,
        optimalCells: 21,
        optimalSwitchCells: 7,
        wrenches: 5,
        puzzleString: "hhOja2R2OBaOjo2R2OBo3R6R6R0Gbaa5Gbao"
      }
    ]
  },
  {
    id: "regular-iqaluit",
    title: "Iqaluit",
    playable: true,
    levels: [
      {
        id: "std-inverse",
        title: "Inverse",
        number: 1,
        brief: "",
        family: "regular-iqaluit",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 28,
        optimalCells: 22,
        optimalSwitchCells: 6,
        wrenches: 7,
        puzzleString: "hh7Obi5OboR5RR2Gpav2RR5RGeaC5GeaC"
      },
      {
        id: "std-totemPole",
        title: "Totem Pole",
        number: 2,
        brief: "",
        family: "regular-iqaluit",
        width: 7,
        height: 7,
        railLimit: 28,
        optimalRails: 14,
        optimalCells: 11,
        optimalSwitchCells: 3,
        wrenches: 5,
        puzzleString: "hh3Geby00OBh6OBa6Oja6Ojh"
      },
      {
        id: "std-western",
        title: "Western",
        number: 3,
        brief: "",
        family: "regular-iqaluit",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 33,
        optimalCells: 26,
        optimalSwitchCells: 7,
        wrenches: 6,
        puzzleString: "hhOjh2R4Ojo1R1Giaa4R4Oja3Gibj4R4Ojh1R1Giao1Ojo2R2Gbah"
      },
      {
        id: "std-collider",
        title: "Collider",
        number: 4,
        brief: "",
        family: "regular-iqaluit",
        width: 7,
        height: 7,
        railLimit: 38,
        optimalRails: 19,
        optimalCells: 13,
        optimalSwitchCells: 6,
        wrenches: 6,
        puzzleString: "hh04Ojh5OBoOjh2GpfGGG2OBoOjh5OBo0"
      },
      {
        id: "std-starshipSandwich",
        title: "Starship Sandwich",
        number: 5,
        brief: "",
        family: "regular-iqaluit",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 33,
        optimalCells: 23,
        optimalSwitchCells: 10,
        wrenches: 6,
        puzzleString: "hhGcbO6Oja6Oja6RRRRRR1Ojo6Ojo6GcbO"
      },
      {
        id: "std-theClassic",
        title: "The Classic",
        number: 6,
        brief: "",
        family: "regular-iqaluit",
        width: 7,
        height: 7,
        railLimit: 38,
        optimalRails: 19,
        optimalCells: 12,
        optimalSwitchCells: 7,
        wrenches: 7,
        puzzleString: "hh3GeaCGeav0Oja03Oki02GbaCOjo"
      }
    ]
  },
  {
    id: "regular-joliette",
    title: "Joliette",
    playable: true,
    levels: [
      {
        id: "std-redPear",
        title: "Red Pear",
        number: 1,
        brief: "",
        family: "regular-joliette",
        width: 7,
        height: 7,
        railLimit: 22,
        optimalRails: 11,
        optimalCells: 9,
        optimalSwitchCells: 2,
        wrenches: 2,
        puzzleString: "hhPaj00OjC5Giaa00"
      },
      {
        id: "std-paintTheTown",
        title: "Paint The Town",
        number: 2,
        brief: "",
        family: "regular-joliette",
        width: 7,
        height: 7,
        railLimit: 28,
        optimalRails: 14,
        optimalCells: 13,
        optimalSwitchCells: 1,
        wrenches: 4,
        puzzleString: "hhOsh5Oso07Pao00Gbav"
      },
      {
        id: "std-lopsided",
        title: "Lopsided",
        number: 3,
        brief: "",
        family: "regular-joliette",
        width: 7,
        height: 7,
        railLimit: 32,
        optimalRails: 16,
        optimalCells: 14,
        optimalSwitchCells: 2,
        wrenches: 5,
        puzzleString: "hh3GiavGcav02RR5RR5RR5PbxPap5OavOav"
      },
      {
        id: "std-plus",
        title: "Plus",
        number: 4,
        brief: "",
        family: "regular-joliette",
        width: 7,
        height: 7,
        railLimit: 38,
        optimalRails: 19,
        optimalCells: 15,
        optimalSwitchCells: 4,
        wrenches: 6,
        puzzleString: "hhPaj06R3Oah1RROjo5R0GdaJ"
      },
      {
        id: "std-orangeWall",
        title: "Orange Wall",
        number: 5,
        brief: "",
        family: "regular-joliette",
        width: 7,
        height: 7,
        railLimit: 48,
        optimalRails: 24,
        optimalCells: 19,
        optimalSwitchCells: 5,
        wrenches: 7,
        puzzleString: "hh6Giav3Pdo6Gbav3Obq2Pdw2Otq3Geav6Pdo3Gcav"
      }
    ]
  },
  {
    id: "regular-kamloops",
    title: "Kamloops",
    playable: true,
    levels: [
      {
        id: "std-poddedPeas",
        title: "Podded Peas",
        number: 1,
        brief: "",
        family: "regular-kamloops",
        width: 7,
        height: 7,
        railLimit: 32,
        optimalRails: 16,
        optimalCells: 14,
        optimalSwitchCells: 2,
        wrenches: 4,
        puzzleString: "hh3GebG004OsJ5OsJ7Pbh5Pcv"
      },
      {
        id: "std-letThemYellow",
        title: "Let Them Yellow",
        number: 2,
        brief: "",
        family: "regular-kamloops",
        width: 7,
        height: 7,
        railLimit: 46,
        optimalRails: 23,
        optimalCells: 18,
        optimalSwitchCells: 5,
        wrenches: 7,
        puzzleString: "hhGeah5Geah04RRRPboRRR04Gbah2OdOO2Gbah"
      },
      {
        id: "std-theOriginal",
        title: "The Original",
        number: 3,
        brief: "",
        family: "regular-kamloops",
        width: 7,
        height: 7,
        railLimit: 36,
        optimalRails: 18,
        optimalCells: 13,
        optimalSwitchCells: 5,
        wrenches: 7,
        puzzleString: "hh07ObqOah5GebOGeaC002OBa"
      },
      {
        id: "std-stuckToYou",
        title: "Stuck To You",
        number: 4,
        brief: "",
        family: "regular-kamloops",
        width: 7,
        height: 7,
        railLimit: 30,
        optimalRails: 15,
        optimalCells: 12,
        optimalSwitchCells: 3,
        wrenches: 7,
        puzzleString: "hh04OjJ5RR2Pco2GiaCOjJ2Pbo2R0"
      },
      {
        id: "std-diagonalMirror",
        title: "Diagonal Mirror",
        number: 5,
        brief: "",
        family: "regular-kamloops",
        width: 7,
        height: 7,
        railLimit: 44,
        optimalRails: 22,
        optimalCells: 17,
        optimalSwitchCells: 5,
        wrenches: 7,
        puzzleString: "hh01OaoGdah5ROjo4R5R5Pbr0"
      },
      {
        id: "std-fourShadowing",
        title: "Four Shadowing",
        number: 6,
        brief: "",
        family: "regular-kamloops",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 25,
        optimalCells: 17,
        optimalSwitchCells: 8,
        wrenches: 8,
        puzzleString: "hhOvaa06Pbo5Pcw1Pdw5Peo06Gbdpz"
      },
      {
        id: "std-fireballIsland",
        title: "Fireball Island",
        number: 7,
        brief: "",
        family: "regular-kamloops",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 34,
        optimalCells: 26,
        optimalSwitchCells: 8,
        wrenches: 10,
        puzzleString: "hhGgbG8R1Oaa7Ojh7R5Ojh3R1Oso2Gdby"
      }
    ]
  },
  {
    id: "regular-london",
    title: "London",
    playable: true,
    levels: [
      {
        id: "std-roundTheTwist",
        title: "Round The Twist",
        number: 1,
        brief: "",
        family: "regular-london",
        width: 7,
        height: 7,
        railLimit: 32,
        optimalRails: 16,
        optimalCells: 12,
        optimalSwitchCells: 4,
        wrenches: 3,
        puzzleString: "hh004Sc07Gbaa2OaJ2Gbao"
      },
      {
        id: "std-moreIsMerrier",
        title: "More Is Merrier",
        number: 2,
        brief: "",
        family: "regular-london",
        width: 7,
        height: 7,
        railLimit: 22,
        optimalRails: 11,
        optimalCells: 9,
        optimalSwitchCells: 2,
        wrenches: 4,
        puzzleString: "hh001OmGG2Sa2GibqGcdii5Gibq0"
      },
      {
        id: "std-threePeas",
        title: "Three Peas",
        number: 3,
        brief: "",
        family: "regular-london",
        width: 7,
        height: 7,
        railLimit: 30,
        optimalRails: 15,
        optimalCells: 12,
        optimalSwitchCells: 3,
        wrenches: 4,
        puzzleString: "hh4Gecih02OBC6OBCSb5OBC04Gbcqo"
      },
      {
        id: "std-akeeTree",
        title: "Ackee Tree",
        number: 4,
        brief: "",
        family: "regular-london",
        width: 7,
        height: 7,
        railLimit: 24,
        optimalRails: 12,
        optimalCells: 11,
        optimalSwitchCells: 1,
        wrenches: 5,
        puzzleString: "hh3OsC6Sa6Gcao6Gibi6Gcaa6Sc6Oav"
      },
      {
        id: "std-hookshot",
        title: "Hookshot",
        number: 5,
        brief: "",
        family: "regular-london",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 25,
        optimalCells: 20,
        optimalSwitchCells: 5,
        wrenches: 6,
        puzzleString: "hh8Oao3GcaC01Sb01Giaa3Osv"
      },
      {
        id: "std-pickYourPartner",
        title: "Pick Your Partner",
        number: 6,
        brief: "",
        family: "regular-london",
        width: 7,
        height: 7,
        railLimit: 44,
        optimalRails: 22,
        optimalCells: 18,
        optimalSwitchCells: 4,
        wrenches: 7,
        puzzleString: "hhGcao6Gcao6Gcao2Sc2GiaaRRR1RRR7OjJ1Sd3OBo"
      },
      {
        id: "std-primer",
        title: "Primer",
        number: 7,
        brief: "",
        family: "regular-london",
        width: 7,
        height: 7,
        railLimit: 36,
        optimalRails: 18,
        optimalCells: 15,
        optimalSwitchCells: 3,
        wrenches: 8,
        puzzleString: "hh3Osh03Sa004Gbah2Gbah2Gbah"
      },
      {
        id: "std-reunited",
        title: "Reunited",
        number: 8,
        brief: "",
        family: "regular-london",
        width: 7,
        height: 7,
        railLimit: 46,
        optimalRails: 23,
        optimalCells: 16,
        optimalSwitchCells: 7,
        wrenches: 9,
        puzzleString: "hh1Sc8OBo03OjJ03GiaJ0"
      },
      {
        id: "std-starStuck",
        title: "Star Stuck",
        number: 9,
        brief: "",
        family: "regular-london",
        width: 7,
        height: 7,
        railLimit: 40,
        optimalRails: 20,
        optimalCells: 14,
        optimalSwitchCells: 6,
        wrenches: 10,
        puzzleString: "hh06Odyy1Gbdco02Pcj6Pad0"
      }
    ]
  },
  {
    id: "regular-mississauga",
    title: "Mississauga",
    playable: true,
    levels: [
      {
        id: "std-warmUp",
        title: "Warm Up",
        number: 1,
        brief: "",
        family: "regular-mississauga",
        width: 7,
        height: 7,
        railLimit: 16,
        optimalRails: 8,
        optimalCells: 7,
        optimalSwitchCells: 1,
        wrenches: 4,
        puzzleString: "hh2GccqhScGicah0009Ocpa1Occh"
      },
      {
        id: "std-theNumerator",
        title: "The Numerator",
        number: 2,
        brief: "",
        family: "regular-mississauga",
        width: 7,
        height: 7,
        railLimit: 34,
        optimalRails: 17,
        optimalCells: 12,
        optimalSwitchCells: 5,
        wrenches: 5,
        puzzleString: "hh2Geah1GeaJ08Sc1Sc08Oav1OaC"
      },
      {
        id: "std-droneVsProbe",
        title: "Drone vs Probe",
        number: 3,
        brief: "",
        family: "regular-mississauga",
        width: 7,
        height: 7,
        railLimit: 30,
        optimalRails: 15,
        optimalCells: 13,
        optimalSwitchCells: 2,
        wrenches: 6,
        puzzleString: "hh3Geah6Sd4PboR3OBo3R7R5Sb2Giah3Gbao"
      },
      {
        id: "std-ochosRios",
        title: "Ochos Rios",
        number: 4,
        brief: "",
        family: "regular-mississauga",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 28,
        optimalCells: 20,
        optimalSwitchCells: 8,
        wrenches: 7,
        puzzleString: "hh8OaJ04GibxSb05OsC"
      },
      {
        id: "std-portCredit",
        title: "Port Credit",
        number: 5,
        brief: "",
        family: "regular-mississauga",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 26,
        optimalCells: 22,
        optimalSwitchCells: 4,
        wrenches: 8,
        puzzleString: "hhGcah2R3Osa2R1Pcw4R03R3Oaa2R1Pbw1Gcao2R"
      },
      {
        id: "std-turtle",
        title: "Turtle",
        number: 6,
        brief: "",
        family: "regular-mississauga",
        width: 7,
        height: 7,
        railLimit: 48,
        optimalRails: 24,
        optimalCells: 17,
        optimalSwitchCells: 7,
        wrenches: 9,
        puzzleString: "hhGcah6GcdojSc06PaoPbo5PfoPeo8Ojh"
      },
      {
        id: "std-factories",
        title: "Factories",
        number: 7,
        brief: "",
        family: "regular-mississauga",
        width: 7,
        height: 7,
        railLimit: 40,
        optimalRails: 20,
        optimalCells: 16,
        optimalSwitchCells: 4,
        wrenches: 10,
        puzzleString: "hh8Pco3Peo9Peo3Pco1Gcao5GiaC1Oby3ObO"
      },
      {
        id: "std-tor",
        title: "Tor",
        number: 8,
        brief: "",
        family: "regular-mississauga",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 32,
        optimalCells: 20,
        optimalSwitchCells: 12,
        wrenches: 10,
        puzzleString: "hh1GeaC1GeaJ1Geav1Oja1Ojh1Ojo9Ojo1Oja1Ojh00"
      }
    ]
  },
  {
    id: "regular-niagara-falls",
    title: "Niagara Falls",
    playable: true,
    levels: [
      {
        id: "std-horhey",
        title: "Horhey",
        number: 1,
        brief: "",
        family: "regular-niagara-falls",
        width: 7,
        height: 7,
        railLimit: 32,
        optimalRails: 16,
        optimalCells: 11,
        optimalSwitchCells: 5,
        wrenches: 8,
        puzzleString: "hh003GiaaGfaaOmaa00"
      },
      {
        id: "std-christmasEve",
        title: "Christmas Eve",
        number: 2,
        brief: "",
        family: "regular-niagara-falls",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 34,
        optimalCells: 24,
        optimalSwitchCells: 10,
        wrenches: 6,
        puzzleString: "hh9OaaGbaCOaa2R1RRR1RR1RRR1RR1RRR1R2OsCGeaaOsC"
      },
      {
        id: "std-candlesticks",
        title: "Candlesticks",
        number: 3,
        brief: "",
        family: "regular-niagara-falls",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 28,
        optimalCells: 18,
        optimalSwitchCells: 10,
        wrenches: 7,
        puzzleString: "hhGeaoGeaoGeah1GeaaGeaaGeah0Sc3RRR1RRR04OaCOaJOav1OavOaJOaC"
      },
      {
        id: "std-argentan",
        title: "Argentan",
        number: 4,
        brief: "",
        family: "regular-niagara-falls",
        width: 7,
        height: 7,
        railLimit: 36,
        optimalRails: 18,
        optimalCells: 13,
        optimalSwitchCells: 5,
        wrenches: 8,
        puzzleString: "hh8Ojh6Ojv6Ojh3Gcbk2Ojv6Ojh0"
      },
      {
        id: "std-wagonWheels",
        title: "Wagon Wheels",
        number: 5,
        brief: "",
        family: "regular-niagara-falls",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 25,
        optimalCells: 18,
        optimalSwitchCells: 7,
        wrenches: 8,
        puzzleString: "hh8Pej1GcaC1Pcx9Gbah1OdWW1Geao9Pbb1Giaa1Pad"
      },
      {
        id: "std-gaius",
        title: "Gaius",
        number: 6,
        brief: "",
        family: "regular-niagara-falls",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 27,
        optimalCells: 21,
        optimalSwitchCells: 6,
        wrenches: 6,
        puzzleString: "hh6OBaGcaaSa0SaGiaaGcaaSa0SaGiaaGcaaSa5Gcaa4SaGiaa"
      },
      {
        id: "std-machineGun",
        title: "Machine Gun",
        number: 7,
        brief: "",
        family: "regular-niagara-falls",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 30,
        optimalCells: 18,
        optimalSwitchCells: 12,
        wrenches: 11,
        puzzleString: "hhGeaaGeaaGeaaGeaaGeaaGeaaGeaa006Sc03Oaa"
      },
      {
        id: "std-humber",
        title: "Humber",
        number: 8,
        brief: "",
        family: "regular-niagara-falls",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 34,
        optimalCells: 24,
        optimalSwitchCells: 10,
        wrenches: 9,
        puzzleString: "hh04OaC5GbbiGcbb2Sc2OBvOsC5Gebq0"
      },
      {
        id: "std-cooksvilleCreek",
        title: "Cooksville Creek",
        number: 9,
        brief: "",
        family: "regular-niagara-falls",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 37,
        optimalCells: 25,
        optimalSwitchCells: 12,
        wrenches: 11,
        puzzleString: "hhOjo5Gidqq7Sb5SdGbdqq5Gbdqq7Sb5SdGbdqq2Sa2Gbdqq"
      }
    ]
  },
  {
    id: "bonus-oakville",
    title: "Oakville",
    playable: true,
    levels: [
      {
        id: "std-rockyRoad",
        title: "Rocky Road",
        number: 1,
        brief: "",
        family: "bonus-oakville",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 28,
        optimalCells: 22,
        optimalSwitchCells: 6,
        wrenches: 10,
        puzzleString: "hhOjh2R2GiaC3R1RR3R1RRRR3RR3R1RR3R1RROjo2R2GiaC"
      },
      {
        id: "std-clownCar",
        title: "Clown Car",
        number: 2,
        brief: "",
        family: "bonus-oakville",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 43,
        optimalCells: 26,
        optimalSwitchCells: 17,
        wrenches: 10,
        puzzleString: "hhOsaOshOso3OBa6OBh6OBo3GplGGyyOO3Ojo6Ojh6Oja3OaoOahOaa"
      },
      {
        id: "std-alleyway",
        title: "Alleyway",
        number: 3,
        brief: "",
        family: "bonus-oakville",
        width: 7,
        height: 7,
        railLimit: 30,
        optimalRails: 15,
        optimalCells: 12,
        optimalSwitchCells: 3,
        wrenches: 6,
        puzzleString: "hh2Osa1Oso5Osh07RRR1RRRGcaQ2Sa2GiaQRRRRRRR"
      },
      {
        id: "std-recyclingGarbage",
        title: "Recycling Garbage",
        number: 4,
        brief: "",
        family: "bonus-oakville",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 25,
        optimalCells: 17,
        optimalSwitchCells: 8,
        wrenches: 8,
        puzzleString: "hhOja5OBC07GpdWW07Ojh5OBo"
      },
      {
        id: "std-shanimal",
        title: "Shanimal",
        number: 5,
        brief: "",
        family: "bonus-oakville",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 30,
        optimalCells: 24,
        optimalSwitchCells: 6,
        wrenches: 11,
        puzzleString: "hh5GibfR5ROta2R1R4R1R4R1R2ObqR5RGcbt"
      },
      {
        id: "std-cayman",
        title: "Cayman",
        number: 6,
        brief: "",
        family: "bonus-oakville",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 26,
        optimalCells: 18,
        optimalSwitchCells: 8,
        wrenches: 11,
        puzzleString: "hhGcah6GcfojbSc06PaoPbo5PcoPco8Ojh"
      },
      {
        id: "std-pwrOvrwhlmng",
        title: "Pwr Ovrwhlmng",
        number: 7,
        brief: "",
        family: "bonus-oakville",
        width: 7,
        height: 7,
        railLimit: 48,
        optimalRails: 24,
        optimalCells: 16,
        optimalSwitchCells: 8,
        wrenches: 11,
        puzzleString: "hh3GeahGeah2GcaoSc1Sb02Sb3OBC7GcahSa1Sb6GbaoGbao"
      },
      {
        id: "std-axiom",
        title: "Axiom",
        number: 8,
        brief: "",
        family: "bonus-oakville",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 30,
        optimalCells: 22,
        optimalSwitchCells: 8,
        wrenches: 8,
        puzzleString: "hh2Pcx1Pbj09Sc07GbaCGbaC1Odyy1GbaCGbaC"
      },
      {
        id: "std-jagd",
        title: "Jagd",
        number: 9,
        brief: "",
        family: "bonus-oakville",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 27,
        optimalCells: 17,
        optimalSwitchCells: 10,
        wrenches: 9,
        puzzleString: "hh8Ojh1R4OjJ1R4Ojh1R1Gcbm2OjJ1R4Ojh1R0"
      }
    ]
  },
  {
    id: "bonus-peterborough",
    title: "Peterborough",
    playable: true,
    levels: [
      {
        id: "std-aBarrelRoll",
        title: "A Barrel Roll",
        number: 1,
        brief: "",
        family: "bonus-peterborough",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 36,
        optimalCells: 24,
        optimalSwitchCells: 12,
        wrenches: 12,
        puzzleString: "hh06OEqq1Odbb5GpbN5Ovbb1Omqq0"
      },
      {
        id: "std-klickers",
        title: "Klickers",
        number: 2,
        brief: "",
        family: "bonus-peterborough",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 29,
        optimalCells: 24,
        optimalSwitchCells: 5,
        wrenches: 6,
        puzzleString: "hhRGcbA5OvboR7R7R7R7R"
      },
      {
        id: "std-hazard",
        title: "Hazard",
        number: 3,
        brief: "",
        family: "bonus-peterborough",
        width: 7,
        height: 7,
        railLimit: 48,
        optimalRails: 24,
        optimalCells: 19,
        optimalSwitchCells: 5,
        wrenches: 8,
        puzzleString: "hhROsh7R1R1Oah6RR2R2OBh5R1Ojh2R8RGbah"
      },
      {
        id: "std-squelchen",
        title: "Squelchen",
        number: 4,
        brief: "",
        family: "bonus-peterborough",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 30,
        optimalCells: 21,
        optimalSwitchCells: 9,
        wrenches: 11,
        puzzleString: "hh5GibDR5ROtO2RPao5Pck1Pew5PboR2ObOR5RGcbc"
      },
      {
        id: "std-miniyowe",
        title: "Mini-Yo-We",
        number: 5,
        brief: "",
        family: "bonus-peterborough",
        width: 7,
        height: 7,
        railLimit: 40,
        optimalRails: 20,
        optimalCells: 13,
        optimalSwitchCells: 7,
        wrenches: 11,
        puzzleString: "hh04OjC1PawPcw2GiaJOjC1PcwPaw2GiaJOjC1PawPcw2GiaJ0"
      },
      {
        id: "std-asymmetric",
        title: "Asymmetric",
        number: 6,
        brief: "",
        family: "bonus-peterborough",
        width: 7,
        height: 7,
        railLimit: 40,
        optimalRails: 20,
        optimalCells: 15,
        optimalSwitchCells: 5,
        wrenches: 11,
        puzzleString: "hh02Geaa4Sa3Oav1RRR1Osv3Sc4Gbah0"
      },
      {
        id: "std-lornePark",
        title: "Lorne Park",
        number: 7,
        brief: "",
        family: "bonus-peterborough",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 41,
        optimalCells: 24,
        optimalSwitchCells: 17,
        wrenches: 12,
        puzzleString: "hhOja5OBoOjh5OBhOjo5OBa3Gecbo3Ojo5OBaOjh5OBhOja5OBo"
      },
      {
        id: "std-adama",
        title: "Adama",
        number: 8,
        brief: "",
        family: "bonus-peterborough",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 36,
        optimalCells: 24,
        optimalSwitchCells: 12,
        wrenches: 13,
        puzzleString: "hh4OsC1OBvGcaaSa0SaGiahGcahSa0SaGiaaGcaaSa5Gcav4SaGiao"
      },
      {
        id: "std-tonelympics",
        title: "Tonelympics",
        number: 9,
        brief: "",
        family: "bonus-peterborough",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 34,
        optimalCells: 24,
        optimalSwitchCells: 10,
        wrenches: 13,
        puzzleString: "hhRGcav5OsaRGcaJ5OshRGcav5OsoRGcaJ5OsaR7R"
      }
    ]
  },
  {
    id: "bonus-quebec-city",
    title: "Quebec City",
    playable: true,
    levels: [
      {
        id: "std-picnic",
        title: "Picnic",
        number: 1,
        brief: "",
        family: "bonus-quebec-city",
        width: 7,
        height: 7,
        railLimit: 44,
        optimalRails: 22,
        optimalCells: 13,
        optimalSwitchCells: 9,
        wrenches: 7,
        puzzleString: "hh04Oka5GiavOki5GibOOkq5GiaC0"
      },
      {
        id: "std-spindle",
        title: "Spindle",
        number: 2,
        brief: "",
        family: "bonus-quebec-city",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 30,
        optimalCells: 22,
        optimalSwitchCells: 8,
        wrenches: 8,
        puzzleString: "hh01R3RGbaCOaaGcao4OBhROjC4GiaaOsoGeahR3R6R"
      },
      {
        id: "std-fireEyed",
        title: "Fire Eyed",
        number: 3,
        brief: "",
        family: "bonus-quebec-city",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 38,
        optimalCells: 30,
        optimalSwitchCells: 8,
        wrenches: 7,
        puzzleString: "hh3Geav3Oah5Oaa8OBa3Ojh8Osh5Osa3Gbav"
      },
      {
        id: "std-rebelt",
        title: "Rebelt",
        number: 4,
        brief: "",
        family: "bonus-quebec-city",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 27,
        optimalCells: 16,
        optimalSwitchCells: 11,
        wrenches: 10,
        puzzleString: "hh2GeahGebqGeav09ScPdx9OjC5OBC"
      },
      {
        id: "std-rgb",
        title: "RGB",
        number: 5,
        brief: "",
        family: "bonus-quebec-city",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 30,
        optimalCells: 19,
        optimalSwitchCells: 11,
        wrenches: 11,
        puzzleString: "hh04GbaoGbaCGbaa1GbaaGbaCGbaoOsaOsCOso1OsoOsCOsa0"
      },
      {
        id: "std-drLinus",
        title: "Dr. Linus",
        number: 6,
        brief: "",
        family: "bonus-quebec-city",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 35,
        optimalCells: 23,
        optimalSwitchCells: 12,
        wrenches: 11,
        puzzleString: "hh0GbaJ5ObiROba3RRRRR3OsaROso5Geby0"
      },
      {
        id: "std-glockenspiel",
        title: "Glockenspiel",
        number: 7,
        brief: "",
        family: "bonus-quebec-city",
        width: 7,
        height: 7,
        railLimit: 36,
        optimalRails: 18,
        optimalCells: 13,
        optimalSwitchCells: 5,
        wrenches: 11,
        puzzleString: "hhPbj2Sc2OuGC04Sb2Gpiacqih2Sd04Pcb2Sa2Pav"
      },
      {
        id: "std-jamboree",
        title: "Jamboree",
        number: 8,
        brief: "",
        family: "bonus-quebec-city",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 28,
        optimalCells: 19,
        optimalSwitchCells: 9,
        wrenches: 12,
        puzzleString: "hhPcj03PcoGebp6SdGfaCOmaa3PboGbbp02Pbb"
      },
      {
        id: "std-licoriceAllsorts",
        title: "Licorice Allsorts",
        number: 9,
        brief: "",
        family: "bonus-quebec-city",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 38,
        optimalCells: 23,
        optimalSwitchCells: 15,
        wrenches: 13,
        puzzleString: "hh001GbaJGbaCGbavGbaoGbahGbaa1OsaOshOsoOsvOsCOsJ0"
      }
    ]
  },
  {
    id: "bonus-regina",
    title: "Regina",
    playable: true,
    levels: [
      {
        id: "std-sangreGrande",
        title: "Sangre Grande",
        number: 1,
        brief: "",
        family: "bonus-regina",
        width: 7,
        height: 7,
        railLimit: 46,
        optimalRails: 23,
        optimalCells: 16,
        optimalSwitchCells: 7,
        wrenches: 7,
        puzzleString: "hh8OsaOsaOsaOsaOao009GbbJ"
      },
      {
        id: "std-theVariable",
        title: "The Variable",
        number: 2,
        brief: "",
        family: "bonus-regina",
        width: 7,
        height: 7,
        railLimit: 48,
        optimalRails: 24,
        optimalCells: 18,
        optimalSwitchCells: 6,
        wrenches: 7,
        puzzleString: "hh8Oka3OBa9Giav3Gcbb9Ojh3OCi"
      },
      {
        id: "std-orff",
        title: "Orff",
        number: 3,
        brief: "",
        family: "bonus-regina",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 38,
        optimalCells: 23,
        optimalSwitchCells: 15,
        wrenches: 8,
        puzzleString: "hhGeaaGeahGeah1GeahGeahGeao05Sc3Sc05OaaOahOao1OaaOahOao"
      },
      {
        id: "std-somewhere",
        title: "Somewhere",
        number: 4,
        brief: "",
        family: "bonus-regina",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 34,
        optimalCells: 22,
        optimalSwitchCells: 12,
        wrenches: 10,
        puzzleString: "hhGcfdlt5Pax5Pfc5Pco5Pec5Pbo5Pdc5Pab5Ofdlt"
      },
      {
        id: "std-usector",
        title: "U-Sector",
        number: 5,
        brief: "",
        family: "bonus-regina",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 36,
        optimalCells: 27,
        optimalSwitchCells: 9,
        wrenches: 11,
        puzzleString: "hh9RRRR1OaJGbav5RR2Sb2OsCGebq7RRRR"
      },
      {
        id: "std-takingTrash",
        title: "Taking Trash",
        number: 6,
        brief: "",
        family: "bonus-regina",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 29,
        optimalCells: 18,
        optimalSwitchCells: 11,
        wrenches: 11,
        puzzleString: "hhOja6Ojh6Ojo9Sa9Giaa6GiahGdcWQ5Giao"
      },
      {
        id: "std-theQuotient",
        title: "The Quotient",
        number: 7,
        brief: "",
        family: "bonus-regina",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 27,
        optimalCells: 19,
        optimalSwitchCells: 8,
        wrenches: 12,
        puzzleString: "hh2Gedqa1GebD08Sc1Sc06Oav1OaJ1OaC1OaC"
      },
      {
        id: "std-trinidad",
        title: "Trinidad",
        number: 8,
        brief: "",
        family: "bonus-regina",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 28,
        optimalCells: 19,
        optimalSwitchCells: 9,
        wrenches: 13,
        puzzleString: "hhOja5OBh0Sd3GcaC1ScGpdbpSa5Sb0Ojo5OBC"
      },
      {
        id: "std-theDenominator",
        title: "The Denominator",
        number: 9,
        brief: "",
        family: "bonus-regina",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 37,
        optimalCells: 23,
        optimalSwitchCells: 14,
        wrenches: 15,
        puzzleString: "hh06ScGkbcSc08Oah1Oah2ROavROaCROavGbah"
      }
    ]
  },
  {
    id: "bonus-st-john-s",
    title: "St. John's",
    playable: true,
    levels: [
      {
        id: "std-backToBasics",
        title: "Back To Basics",
        number: 1,
        brief: "",
        family: "bonus-st-john-s",
        width: 7,
        height: 7,
        railLimit: 40,
        optimalRails: 20,
        optimalCells: 16,
        optimalSwitchCells: 4,
        wrenches: 6,
        puzzleString: "hh05Obi1ROso08Osa4GcdyG"
      },
      {
        id: "std-theConstant",
        title: "The Constant",
        number: 2,
        brief: "",
        family: "bonus-st-john-s",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 37,
        optimalCells: 29,
        optimalSwitchCells: 8,
        wrenches: 8,
        puzzleString: "hh8Oka3OBa2RR1RR2GiavR1RGcbb2RR1RR2Ojh3OCi"
      },
      {
        id: "std-willow",
        title: "Willow",
        number: 3,
        brief: "",
        family: "bonus-st-john-s",
        width: 7,
        height: 7,
        railLimit: 32,
        optimalRails: 16,
        optimalCells: 10,
        optimalSwitchCells: 6,
        wrenches: 9,
        puzzleString: "hh3Gebo00001Ohoooo"
      },
      {
        id: "std-conquistador",
        title: "Conquistador",
        number: 4,
        brief: "",
        family: "bonus-st-john-s",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 28,
        optimalCells: 18,
        optimalSwitchCells: 10,
        wrenches: 12,
        puzzleString: "hh05Glao3OBCPao1GkaJ3OCG2Goaa3OBCPco0"
      },
      {
        id: "std-squier",
        title: "Squier",
        number: 5,
        brief: "",
        family: "bonus-st-john-s",
        width: 7,
        height: 7,
        railLimit: 38,
        optimalRails: 19,
        optimalCells: 14,
        optimalSwitchCells: 5,
        wrenches: 12,
        puzzleString: "hh6OsC07Sb07GdbG"
      },
      {
        id: "std-oakwoodAve",
        title: "Oakwood Ave",
        number: 6,
        brief: "",
        family: "bonus-st-john-s",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 33,
        optimalCells: 24,
        optimalSwitchCells: 9,
        wrenches: 12,
        puzzleString: "hhGcaJ2Sc2OBv04PacRRRRRPcc04Ojv2Sa2GiaJ"
      },
      {
        id: "std-erindale",
        title: "Erindale",
        number: 7,
        brief: "",
        family: "bonus-st-john-s",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 45,
        optimalCells: 31,
        optimalSwitchCells: 14,
        wrenches: 13,
        puzzleString: "hh8Oaa4Gbaa1Ojv4GiaCGfbiOjh2Sd1Giah1OjC4Giav1Oso4Geao"
      }
    ]
  },
  {
    id: "bonus-toronto",
    title: "Toronto",
    playable: true,
    levels: [
      {
        id: "std-sliceOfLife",
        title: "Slice of Life",
        number: 1,
        brief: "",
        family: "bonus-toronto",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 27,
        optimalCells: 17,
        optimalSwitchCells: 10,
        wrenches: 13,
        puzzleString: "hh1OjC1Osa09SaSd00GbdmK"
      },
      {
        id: "std-mrMorgan",
        title: "Mr. Morgan",
        number: 2,
        brief: "",
        family: "bonus-toronto",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 32,
        optimalCells: 24,
        optimalSwitchCells: 8,
        wrenches: 13,
        puzzleString: "hhGcdaaSc04OaC1Pax5Oav5Sb1Oao4Gbdaa4Gbcaa"
      },
      {
        id: "std-chief",
        title: "Chief",
        number: 3,
        brief: "",
        family: "bonus-toronto",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 27,
        optimalCells: 19,
        optimalSwitchCells: 8,
        wrenches: 15,
        puzzleString: "hh02OBh3R1RGeaaGeahSb5Sd1GiahR4GbaaOjv0"
      },
      {
        id: "std-waterfall",
        title: "Waterfall",
        number: 4,
        brief: "",
        family: "bonus-toronto",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 27,
        optimalCells: 17,
        optimalSwitchCells: 10,
        wrenches: 7,
        puzzleString: "hhOsoROsoROsoROso1Oso1Oso1Oso0002Gbao"
      },
      {
        id: "std-volcano",
        title: "Volcano",
        number: 5,
        brief: "",
        family: "bonus-toronto",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 32,
        optimalCells: 22,
        optimalSwitchCells: 10,
        wrenches: 12,
        puzzleString: "hh9OBa1Oja4ROaaR4OBaROja5Osa03Gbaa"
      },
      {
        id: "std-norwich",
        title: "Norwich",
        number: 6,
        brief: "",
        family: "bonus-toronto",
        width: 7,
        height: 7,
        railLimit: 46,
        optimalRails: 23,
        optimalCells: 18,
        optimalSwitchCells: 5,
        wrenches: 10,
        puzzleString: "hh3Pew6Pcw6R3GcaJ2R1OEffGfbG3R6Pbw6Pfw"
      },
      {
        id: "std-threeBelow",
        title: "Three Below",
        number: 7,
        brief: "",
        family: "bonus-toronto",
        width: 7,
        height: 7,
        railLimit: 40,
        optimalRails: 20,
        optimalCells: 13,
        optimalSwitchCells: 7,
        wrenches: 13,
        puzzleString: "hh2GeaJOvyyGeaC000RRPaoPboPcoRRRR3RR"
      }
    ]
  },
  {
    id: "bonus-uxbridge",
    title: "Uxbridge",
    playable: true,
    levels: [
      {
        id: "std-mockingbird",
        title: "Mockingbird",
        number: 1,
        brief: "",
        family: "bonus-uxbridge",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 46,
        optimalCells: 30,
        optimalSwitchCells: 16,
        wrenches: 15,
        puzzleString: "hh1GiavR2GiavGeao2R6Sc4RRSb3OEEx2Sa6R5GiaCR2GiaCGbao"
      },
      {
        id: "std-drummerBoy",
        title: "Drummer Boy",
        number: 2,
        brief: "",
        family: "bonus-uxbridge",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 36,
        optimalCells: 24,
        optimalSwitchCells: 12,
        wrenches: 12,
        puzzleString: "hhPap4ScGibq6R5SaGibqOjh4PbwGiah5ScGiba6RPch4SaGiba"
      },
      {
        id: "std-forestAve",
        title: "Forest Ave",
        number: 3,
        brief: "",
        family: "bonus-uxbridge",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 42,
        optimalCells: 25,
        optimalSwitchCells: 17,
        wrenches: 12,
        puzzleString: "hhGcaC5OBoGcaC5OBoGcaC5OBoGcaC2Pbo2OBhGcaC5OBoGcaC5OBoGcaC5OBo"
      },
      {
        id: "std-parachute",
        title: "Parachute",
        number: 4,
        brief: "",
        family: "bonus-uxbridge",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 40,
        optimalCells: 26,
        optimalSwitchCells: 14,
        wrenches: 13,
        puzzleString: "hhOjJ5OBJGcah5GiaC2Pco1Pao5R5Peo1Pbo2Gcaa5GiaoOjJ5OBJ"
      },
      {
        id: "std-theQuest",
        title: "The Quest",
        number: 5,
        brief: "",
        family: "bonus-uxbridge",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 37,
        optimalCells: 22,
        optimalSwitchCells: 15,
        wrenches: 13,
        puzzleString: "hhGeah4GeaoGeaJSb02Peo03SdSb6Gbaa4GbaoOaJ"
      },
      {
        id: "std-kes",
        title: "Kes",
        number: 6,
        brief: "",
        family: "bonus-uxbridge",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 39,
        optimalCells: 24,
        optimalSwitchCells: 15,
        wrenches: 15,
        puzzleString: "hhGeah2Geaa2Geao04PcoPaoPaoPaoPaoPaoPbo04GbahOaJOaJOaJOaJOaJGbao"
      }
    ]
  },
  {
    id: "bonus-vancouver",
    title: "Vancouver",
    playable: true,
    levels: [
      {
        id: "std-exhibitionStation",
        title: "Exhibition Station",
        number: 1,
        brief: "",
        family: "bonus-vancouver",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 37,
        optimalCells: 25,
        optimalSwitchCells: 12,
        wrenches: 20,
        puzzleString: "hh9RRR4GebtRGebw5R3Oty2R2OtO3R3Pbh2R2Pcv"
      },
      {
        id: "std-transmogrify",
        title: "Transmogrify",
        number: 2,
        brief: "",
        family: "bonus-vancouver",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 32,
        optimalCells: 22,
        optimalSwitchCells: 10,
        wrenches: 20,
        puzzleString: "hhOjC3GcaJ2OjC3Giav2OjC3GcaJ2OjC3Giav6R6RPdoPfo"
      },
      {
        id: "std-magicCarpet",
        title: "Magic Carpet",
        number: 3,
        brief: "",
        family: "bonus-vancouver",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 39,
        optimalCells: 26,
        optimalSwitchCells: 13,
        wrenches: 20,
        puzzleString: "hh01OBaR4OBhROsa3OBCROsh3OBoROsC4ROso0Gjdbs"
      },
      {
        id: "std-dropOff",
        title: "Drop Off",
        number: 4,
        brief: "",
        family: "bonus-vancouver",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 34,
        optimalCells: 19,
        optimalSwitchCells: 15,
        wrenches: 15,
        puzzleString: "hh04GcdaaSc4OBa6GiavGcdiiSa4OBh0"
      },
      {
        id: "std-doppelganger",
        title: "Doppelganger",
        number: 5,
        brief: "",
        family: "bonus-vancouver",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 44,
        optimalCells: 26,
        optimalSwitchCells: 18,
        wrenches: 20,
        puzzleString: "hh04Oja1Oja1Giaa1OBaOjC1Giah1Ojh1GiaCOjo1Ojo1Giao1OBo0"
      }
    ]
  },
  {
    id: "bonus-whitehorse",
    title: "Whitehorse",
    playable: true,
    levels: [
      {
        id: "std-circleSquare",
        title: "Circle Square",
        number: 1,
        brief: "",
        family: "bonus-whitehorse",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 36,
        optimalCells: 25,
        optimalSwitchCells: 11,
        wrenches: 25,
        puzzleString: "hh06OBo1OjC2Gccbo2Sd2Gicbo2OBv1Oja0"
      },
      {
        id: "std-indusblue",
        title: "Indusblue",
        number: 2,
        brief: "",
        family: "bonus-whitehorse",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 34,
        optimalCells: 23,
        optimalSwitchCells: 11,
        wrenches: 25,
        puzzleString: "hhOjh2Osh2OBh04Ojh2GphWWWW2OBh04Ojh2Oao2OBh"
      },
      {
        id: "std-bramblewoodLane",
        title: "Bramblewood Lane",
        number: 3,
        brief: "",
        family: "bonus-whitehorse",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 36,
        optimalCells: 26,
        optimalSwitchCells: 10,
        wrenches: 30,
        puzzleString: "hhGcbi2R3Osa2R1Pcw4R3Oka9R3Oaa2R1Pbw1Gcbq2R"
      },
      {
        id: "std-turing",
        title: "Turing",
        number: 4,
        brief: "",
        family: "bonus-whitehorse",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 27,
        optimalCells: 17,
        optimalSwitchCells: 10,
        wrenches: 25,
        puzzleString: "hh6GmcGC0Pbo3Ojh2Sd6Gbcih06Ocqo"
      },
      {
        id: "std-focusPocus",
        title: "Focus Pocus",
        number: 5,
        brief: "",
        family: "bonus-whitehorse",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 38,
        optimalCells: 27,
        optimalSwitchCells: 11,
        wrenches: 20,
        puzzleString: "hh05Otb1Oto1Otp9Gbby1GbbO1GbbG0"
      }
    ]
  },
  {
    id: "express-british-columbia",
    title: "British Columbia",
    playable: true,
    levels: [
      {
        id: "std-greenLine",
        title: "Green Line",
        number: 1,
        brief: "",
        family: "express-british-columbia",
        width: 7,
        height: 7,
        railLimit: 6,
        optimalRails: 3,
        optimalCells: 3,
        optimalSwitchCells: 0,
        wrenches: 1,
        puzzleString: "hh002OjC3GiaC00"
      },
      {
        id: "std-theThree",
        title: "The Three",
        number: 2,
        brief: "",
        family: "express-british-columbia",
        width: 7,
        height: 7,
        railLimit: 24,
        optimalRails: 12,
        optimalCells: 10,
        optimalSwitchCells: 2,
        wrenches: 1,
        puzzleString: "hh3Osh5Osa1Oso005Gbaa1Gbao5Gbah"
      },
      {
        id: "std-pureMagic",
        title: "Pure Magic",
        number: 3,
        brief: "",
        family: "express-british-columbia",
        width: 7,
        height: 7,
        railLimit: 20,
        optimalRails: 10,
        optimalCells: 9,
        optimalSwitchCells: 1,
        wrenches: 1,
        puzzleString: "hh3OsC07OjC5GiaC07GbaC"
      },
      {
        id: "std-twoLiner",
        title: "Two Liner",
        number: 4,
        brief: "",
        family: "express-british-columbia",
        width: 7,
        height: 7,
        railLimit: 12,
        optimalRails: 6,
        optimalCells: 6,
        optimalSwitchCells: 0,
        wrenches: 1,
        puzzleString: "hh0GiaC01OaC3Geaa01Oja0"
      },
      {
        id: "std-theLittleOne",
        title: "The Little One",
        number: 5,
        brief: "",
        family: "express-british-columbia",
        width: 7,
        height: 7,
        railLimit: 12,
        optimalRails: 6,
        optimalCells: 6,
        optimalSwitchCells: 0,
        wrenches: 1,
        puzzleString: "hh004OaJ6GeaJ0"
      }
    ]
  },
  {
    id: "express-alberta",
    title: "Alberta",
    playable: true,
    levels: [
      {
        id: "std-aHardPlace",
        title: "A Hard Place",
        number: 1,
        brief: "",
        family: "express-alberta",
        width: 7,
        height: 7,
        railLimit: 14,
        optimalRails: 7,
        optimalCells: 7,
        optimalSwitchCells: 0,
        wrenches: 1,
        puzzleString: "hh001Oja2R2Giaa00"
      },
      {
        id: "std-youDid",
        title: "You Did",
        number: 2,
        brief: "",
        family: "express-alberta",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 27,
        optimalCells: 25,
        optimalSwitchCells: 2,
        wrenches: 1,
        puzzleString: "hhGcah6RRRRRR1Ojh09Giaa1RRRRRR6OBa"
      },
      {
        id: "std-traveller",
        title: "Traveller",
        number: 3,
        brief: "",
        family: "express-alberta",
        width: 7,
        height: 7,
        railLimit: 22,
        optimalRails: 11,
        optimalCells: 11,
        optimalSwitchCells: 0,
        wrenches: 1,
        puzzleString: "hhOjo2R8R2R9R7R3R0Gjao"
      },
      {
        id: "std-inTheMiddle",
        title: "In The Middle",
        number: 4,
        brief: "",
        family: "express-alberta",
        width: 7,
        height: 7,
        railLimit: 26,
        optimalRails: 13,
        optimalCells: 11,
        optimalSwitchCells: 2,
        wrenches: 1,
        puzzleString: "hh8OaJ7Ojh05Giah7GeaJ"
      },
      {
        id: "std-foray",
        title: "Foray",
        number: 5,
        brief: "",
        family: "express-alberta",
        width: 7,
        height: 7,
        railLimit: 36,
        optimalRails: 18,
        optimalCells: 16,
        optimalSwitchCells: 2,
        wrenches: 2,
        puzzleString: "hhOjh5OBa07Gpdhs07Ojo5OBC"
      },
      {
        id: "std-noTouching",
        title: "No Touching",
        number: 6,
        brief: "",
        family: "express-alberta",
        width: 7,
        height: 7,
        railLimit: 24,
        optimalRails: 12,
        optimalCells: 10,
        optimalSwitchCells: 2,
        wrenches: 2,
        puzzleString: "hh3Osa07Gcah5OBh07Gbaa"
      },
      {
        id: "std-twoForTwo",
        title: "Two For Two",
        number: 7,
        brief: "",
        family: "express-alberta",
        width: 7,
        height: 7,
        railLimit: 30,
        optimalRails: 15,
        optimalCells: 15,
        optimalSwitchCells: 0,
        wrenches: 1,
        puzzleString: "hh6RR1R8R2R2R5R3R2R4GbbG2R2ObG"
      }
    ]
  },
  {
    id: "express-saskatchewan",
    title: "Saskatchewan",
    playable: true,
    levels: [
      {
        id: "std-bluesy",
        title: "Bluesy",
        number: 1,
        brief: "",
        family: "express-saskatchewan",
        width: 7,
        height: 7,
        railLimit: 24,
        optimalRails: 12,
        optimalCells: 11,
        optimalSwitchCells: 1,
        wrenches: 2,
        puzzleString: "hh8Giao3Gcao005Obq0"
      },
      {
        id: "std-lantern",
        title: "Lantern",
        number: 2,
        brief: "",
        family: "express-saskatchewan",
        width: 7,
        height: 7,
        railLimit: 14,
        optimalRails: 7,
        optimalCells: 6,
        optimalSwitchCells: 1,
        wrenches: 2,
        puzzleString: "hh0Geav03GbaC6Otz0"
      },
      {
        id: "std-boomBah",
        title: "Boom Bah",
        number: 3,
        brief: "",
        family: "express-saskatchewan",
        width: 7,
        height: 7,
        railLimit: 24,
        optimalRails: 12,
        optimalCells: 10,
        optimalSwitchCells: 2,
        wrenches: 3,
        puzzleString: "hh6Geaa04Oth2Gpbi2Obb04Gbaa"
      },
      {
        id: "std-redGreen",
        title: "Red Green",
        number: 4,
        brief: "",
        family: "express-saskatchewan",
        width: 7,
        height: 7,
        railLimit: 28,
        optimalRails: 14,
        optimalCells: 11,
        optimalSwitchCells: 3,
        wrenches: 3,
        puzzleString: "hhGeaa1GeaC1Geaa1GeaC0008OdeC"
      }
    ]
  },
  {
    id: "express-manitoba",
    title: "Manitoba",
    playable: true,
    levels: [
      {
        id: "std-yellowTriangle",
        title: "Yellow Triangle",
        number: 1,
        brief: "",
        family: "express-manitoba",
        width: 7,
        height: 7,
        railLimit: 22,
        optimalRails: 11,
        optimalCells: 9,
        optimalSwitchCells: 2,
        wrenches: 3,
        puzzleString: "hhOsh1Osh3Geah0000"
      },
      {
        id: "std-purpeller",
        title: "Purpeller",
        number: 2,
        brief: "",
        family: "express-manitoba",
        width: 7,
        height: 7,
        railLimit: 32,
        optimalRails: 16,
        optimalCells: 13,
        optimalSwitchCells: 3,
        wrenches: 3,
        puzzleString: "hhOsJ4RR6R00OBJR5GeaJRR"
      },
      {
        id: "std-reflection",
        title: "Reflection",
        number: 3,
        brief: "",
        family: "express-manitoba",
        width: 7,
        height: 7,
        railLimit: 44,
        optimalRails: 22,
        optimalCells: 16,
        optimalSwitchCells: 6,
        wrenches: 3,
        puzzleString: "hhOsa5Gmao7Osa09Oao7Gdaa5Oao"
      },
      {
        id: "std-combinellow",
        title: "Combinellow",
        number: 4,
        brief: "",
        family: "express-manitoba",
        width: 7,
        height: 7,
        railLimit: 34,
        optimalRails: 17,
        optimalCells: 14,
        optimalSwitchCells: 3,
        wrenches: 3,
        puzzleString: "hhR5GeahR6Ojh6R6Ojh6R6RROahROahRR"
      },
      {
        id: "std-colourize",
        title: "Colourize",
        number: 5,
        brief: "",
        family: "express-manitoba",
        width: 7,
        height: 7,
        railLimit: 30,
        optimalRails: 15,
        optimalCells: 14,
        optimalSwitchCells: 1,
        wrenches: 3,
        puzzleString: "hhOsa7Oao0009GjaJ"
      },
      {
        id: "std-weightedTop",
        title: "Weighted Top",
        number: 6,
        brief: "",
        family: "express-manitoba",
        width: 7,
        height: 7,
        railLimit: 34,
        optimalRails: 17,
        optimalCells: 13,
        optimalSwitchCells: 4,
        wrenches: 3,
        puzzleString: "hh3GeaC09OCqROki09GbaC"
      }
    ]
  },
  {
    id: "express-ontario",
    title: "Ontario",
    playable: true,
    levels: [
      {
        id: "std-embrace",
        title: "Embrace",
        number: 1,
        brief: "",
        family: "express-ontario",
        width: 7,
        height: 7,
        railLimit: 26,
        optimalRails: 13,
        optimalCells: 11,
        optimalSwitchCells: 2,
        wrenches: 3,
        puzzleString: "hhOso2GeaJ00001GbaJ2Oaa"
      },
      {
        id: "std-peeGee",
        title: "Pee Gee",
        number: 2,
        brief: "",
        family: "express-ontario",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 26,
        optimalCells: 20,
        optimalSwitchCells: 6,
        wrenches: 4,
        puzzleString: "hhOjh5OBo7GcaJ02GiaCGcaJ03Ojo5OBa"
      },
      {
        id: "std-autumn",
        title: "Autumn",
        number: 3,
        brief: "",
        family: "express-ontario",
        width: 7,
        height: 7,
        railLimit: 34,
        optimalRails: 17,
        optimalCells: 11,
        optimalSwitchCells: 6,
        wrenches: 4,
        puzzleString: "hh2Osa1Geav0009Oah1Oav"
      },
      {
        id: "std-unscathed",
        title: "Unscathed",
        number: 4,
        brief: "",
        family: "express-ontario",
        width: 7,
        height: 7,
        railLimit: 30,
        optimalRails: 15,
        optimalCells: 11,
        optimalSwitchCells: 4,
        wrenches: 4,
        puzzleString: "hh7Gcaa6Ojo6RRR1RRROja6Gcao0"
      },
      {
        id: "std-challenger",
        title: "Challenger",
        number: 5,
        brief: "",
        family: "express-ontario",
        width: 7,
        height: 7,
        railLimit: 28,
        optimalRails: 14,
        optimalCells: 11,
        optimalSwitchCells: 3,
        wrenches: 5,
        puzzleString: "hh3Oto07GcaC5Giav07Obi"
      },
      {
        id: "std-pleaseWait",
        title: "Please Wait",
        number: 6,
        brief: "",
        family: "express-ontario",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 28,
        optimalCells: 23,
        optimalSwitchCells: 5,
        wrenches: 5,
        puzzleString: "hh8OBaRRRR6R6R6R6R5GiaJROao"
      }
    ]
  },
  {
    id: "express-quebec",
    title: "Quebec",
    playable: true,
    levels: [
      {
        id: "std-berlin",
        title: "Berlin",
        number: 1,
        brief: "",
        family: "express-quebec",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 25,
        optimalCells: 21,
        optimalSwitchCells: 4,
        wrenches: 5,
        puzzleString: "hh8GeaJ1Geaa1GeaC8RRR1RRR8OaC1OaJ1Oaa"
      },
      {
        id: "std-golem",
        title: "Golem",
        number: 2,
        brief: "",
        family: "express-quebec",
        width: 7,
        height: 7,
        railLimit: 40,
        optimalRails: 20,
        optimalCells: 16,
        optimalSwitchCells: 4,
        wrenches: 5,
        puzzleString: "hh07Oah5OBCRGcaC5Oso0"
      },
      {
        id: "std-sunburst",
        title: "Sunburst",
        number: 3,
        brief: "",
        family: "express-quebec",
        width: 7,
        height: 7,
        railLimit: 40,
        optimalRails: 20,
        optimalCells: 13,
        optimalSwitchCells: 7,
        wrenches: 5,
        puzzleString: "hh0Osh01Ojh1Gpah1OBh01Oah0"
      },
      {
        id: "std-peaShooter",
        title: "Pea Shooter",
        number: 4,
        brief: "",
        family: "express-quebec",
        width: 7,
        height: 7,
        railLimit: 28,
        optimalRails: 14,
        optimalCells: 11,
        optimalSwitchCells: 3,
        wrenches: 6,
        puzzleString: "hh001OaoOaoOshOsh2GibG00"
      },
      {
        id: "std-scarab",
        title: "Scarab",
        number: 5,
        brief: "",
        family: "express-quebec",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 28,
        optimalCells: 21,
        optimalSwitchCells: 7,
        wrenches: 6,
        puzzleString: "hhGeaC5GeaC0Oso4Ojh3OBa4Oah0Gbav5Gbav"
      }
    ]
  },
  {
    id: "express-new-brunswick",
    title: "New Brunswick",
    playable: true,
    levels: [
      {
        id: "std-prancing",
        title: "Prancing",
        number: 1,
        brief: "",
        family: "express-new-brunswick",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 33,
        optimalCells: 25,
        optimalSwitchCells: 8,
        wrenches: 6,
        puzzleString: "hhOjo5OBa5OjJ01GkbN01OBC5Ojh5OBo"
      },
      {
        id: "std-boxSeven",
        title: "Box Seven",
        number: 2,
        brief: "",
        family: "express-new-brunswick",
        width: 7,
        height: 7,
        railLimit: 36,
        optimalRails: 18,
        optimalCells: 14,
        optimalSwitchCells: 4,
        wrenches: 7,
        puzzleString: "hhOkb6Okq6RRR4RRRR3RRR4GcaC6GcaJ"
      },
      {
        id: "std-sapling",
        title: "Sapling",
        number: 3,
        brief: "",
        family: "express-new-brunswick",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 26,
        optimalCells: 18,
        optimalSwitchCells: 8,
        wrenches: 7,
        puzzleString: "hhGcaa5Giao0005Gcaa5OGccc"
      },
      {
        id: "std-matchUp",
        title: "Match Up",
        number: 4,
        brief: "",
        family: "express-new-brunswick",
        width: 7,
        height: 7,
        railLimit: 48,
        optimalRails: 24,
        optimalCells: 18,
        optimalSwitchCells: 6,
        wrenches: 8,
        puzzleString: "hhGeaJ5Geav07OBoOta06GbaJ5Oah"
      },
      {
        id: "std-beingGreen",
        title: "Being Green",
        number: 5,
        brief: "",
        family: "express-new-brunswick",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 35,
        optimalCells: 25,
        optimalSwitchCells: 10,
        wrenches: 7,
        puzzleString: "hh8Oao3GbaC1OaoR3RGbaCRR3RROshR3RGeaC1Osh3GeaC"
      },
      {
        id: "std-casualty",
        title: "Casualty",
        number: 6,
        brief: "",
        family: "express-new-brunswick",
        width: 7,
        height: 7,
        railLimit: 46,
        optimalRails: 23,
        optimalCells: 15,
        optimalSwitchCells: 8,
        wrenches: 8,
        puzzleString: "hh4Geah9Oja5OBoGcaJ5GibOOja5OBo01Oah"
      }
    ]
  },
  {
    id: "express-prince-edward-island",
    title: "Prince Edward Island",
    playable: true,
    levels: [
      {
        id: "std-niner",
        title: "Niner",
        number: 1,
        brief: "",
        family: "express-prince-edward-island",
        width: 7,
        height: 7,
        railLimit: 36,
        optimalRails: 18,
        optimalCells: 14,
        optimalSwitchCells: 4,
        wrenches: 8,
        puzzleString: "hh07Oaa3GcaC1PboRPco1GiaC3Osa0"
      },
      {
        id: "std-teamwork",
        title: "Teamwork",
        number: 2,
        brief: "",
        family: "express-prince-edward-island",
        width: 7,
        height: 7,
        railLimit: 40,
        optimalRails: 20,
        optimalCells: 16,
        optimalSwitchCells: 4,
        wrenches: 8,
        puzzleString: "hh3Pfw6GkaJ007OaC5OBoROja"
      },
      {
        id: "std-returnPolicing",
        title: "Return Policing",
        number: 3,
        brief: "",
        family: "express-prince-edward-island",
        width: 7,
        height: 7,
        railLimit: 30,
        optimalRails: 15,
        optimalCells: 11,
        optimalSwitchCells: 4,
        wrenches: 8,
        puzzleString: "hh6R5R5R5Pcw5R5R5R4GidqqOdaa"
      },
      {
        id: "std-formatic",
        title: "Formatic",
        number: 4,
        brief: "",
        family: "express-prince-edward-island",
        width: 7,
        height: 7,
        railLimit: 30,
        optimalRails: 15,
        optimalCells: 10,
        optimalSwitchCells: 5,
        wrenches: 8,
        puzzleString: "hh003PboOdaaPco5GobG0"
      },
      {
        id: "std-rainbowArrow",
        title: "Rainbow Arrow",
        number: 5,
        brief: "",
        family: "express-prince-edward-island",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 28,
        optimalCells: 16,
        optimalSwitchCells: 12,
        wrenches: 9,
        puzzleString: "hh0Paw2Giao3Pbw2GiaC3R2OEOO3Pew2Giah3Pcw2Giaa"
      }
    ]
  },
  {
    id: "express-nova-scotia",
    title: "Nova Scotia",
    playable: true,
    levels: [
      {
        id: "std-oneWay",
        title: "One Way",
        number: 1,
        brief: "",
        family: "express-nova-scotia",
        width: 7,
        height: 7,
        railLimit: 36,
        optimalRails: 18,
        optimalCells: 12,
        optimalSwitchCells: 6,
        wrenches: 8,
        puzzleString: "hh03OBo7GcaC1PawPbw2OBo03OBo"
      },
      {
        id: "std-roundabout",
        title: "Roundabout",
        number: 2,
        brief: "",
        family: "express-nova-scotia",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 26,
        optimalCells: 21,
        optimalSwitchCells: 5,
        wrenches: 9,
        puzzleString: "hh0Oah01OBa1GedGO1Ojo3R5R1Oso3R"
      },
      {
        id: "std-chromaShift",
        title: "Chromashift",
        number: 3,
        brief: "",
        family: "express-nova-scotia",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 29,
        optimalCells: 22,
        optimalSwitchCells: 7,
        wrenches: 9,
        puzzleString: "hh05OaC1Paw1Oao2OBC1Gkba1Ojo2OsC1Paw1Oso0"
      },
      {
        id: "std-balsam",
        title: "Balsam",
        number: 4,
        brief: "",
        family: "express-nova-scotia",
        width: 7,
        height: 7,
        railLimit: 36,
        optimalRails: 18,
        optimalCells: 12,
        optimalSwitchCells: 6,
        wrenches: 9,
        puzzleString: "hh07GbbO6Ozaaqq00"
      },
      {
        id: "std-boomerang",
        title: "Boomerang",
        number: 5,
        brief: "",
        family: "express-nova-scotia",
        width: 7,
        height: 7,
        railLimit: 36,
        optimalRails: 18,
        optimalCells: 12,
        optimalSwitchCells: 6,
        wrenches: 9,
        puzzleString: "hh5Pbw6Pew6Pcw7Ouaa00Gbclo"
      }
    ]
  },
  {
    id: "express-newfoundland",
    title: "Newfoundland",
    playable: true,
    levels: [
      {
        id: "std-taxing",
        title: "Taxing",
        number: 1,
        brief: "",
        family: "express-newfoundland",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 26,
        optimalCells: 20,
        optimalSwitchCells: 6,
        wrenches: 8,
        puzzleString: "hhOjo5GmaCOsh0003OaoGdaC5OBh"
      },
      {
        id: "std-dousingTheFlame",
        title: "Dousing The Flame",
        number: 2,
        brief: "",
        family: "express-newfoundland",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 28,
        optimalCells: 19,
        optimalSwitchCells: 9,
        wrenches: 9,
        puzzleString: "hhOsaROsaGeaoOsaROsa1Osa3Osa005Pco0"
      },
      {
        id: "std-duplex",
        title: "Duplex",
        number: 3,
        brief: "",
        family: "express-newfoundland",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 29,
        optimalCells: 18,
        optimalSwitchCells: 11,
        wrenches: 9,
        puzzleString: "hhR5ROjo5OBhR5OBhOjo5ROjo5OBhR5RGcaC5GiaC"
      },
      {
        id: "std-pals",
        title: "Pals",
        number: 4,
        brief: "",
        family: "express-newfoundland",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 31,
        optimalCells: 21,
        optimalSwitchCells: 10,
        wrenches: 9,
        puzzleString: "hhGcbF5GibM05OCi3Oka01Otq0"
      },
      {
        id: "std-refresh",
        title: "Refresh",
        number: 5,
        brief: "",
        family: "express-newfoundland",
        width: 7,
        height: 7,
        railLimit: 38,
        optimalRails: 19,
        optimalCells: 11,
        optimalSwitchCells: 8,
        wrenches: 10,
        puzzleString: "hh04GcaJ2Paw2OBhGcaJ5OBhGcaJ2Pcw2OBh0"
      }
    ]
  },
  {
    id: "express-bonus-yukon",
    title: "Bonus: Yukon",
    playable: true,
    levels: [
      {
        id: "std-partnership",
        title: "Partnership",
        number: 1,
        brief: "",
        family: "express-bonus-yukon",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 30,
        optimalCells: 23,
        optimalSwitchCells: 7,
        wrenches: 8,
        puzzleString: "hh1GiaC1GeaJ1Gcav0007ODqh3Olah"
      },
      {
        id: "std-reciprocate",
        title: "Reciprocate",
        number: 2,
        brief: "",
        family: "express-bonus-yukon",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 40,
        optimalCells: 24,
        optimalSwitchCells: 16,
        wrenches: 10,
        puzzleString: "hh04OavGbaJ3GbaCOavOjJ2R2OBJOsCGeaJ3GeavOsC0"
      },
      {
        id: "std-impact",
        title: "Impact",
        number: 3,
        brief: "",
        family: "express-bonus-yukon",
        width: 7,
        height: 7,
        railLimit: 28,
        optimalRails: 14,
        optimalCells: 12,
        optimalSwitchCells: 2,
        wrenches: 9,
        puzzleString: "hh3GedOO07Omaa5OEqq07GbdOO"
      },
      {
        id: "std-moonbeams",
        title: "Moonbeams",
        number: 4,
        brief: "",
        family: "express-bonus-yukon",
        width: 7,
        height: 7,
        railLimit: 46,
        optimalRails: 23,
        optimalCells: 19,
        optimalSwitchCells: 4,
        wrenches: 10,
        puzzleString: "hh2Pew1Pcw4RRR07OvOO3GedEs0"
      },
      {
        id: "std-sibilant",
        title: "Sibilant",
        number: 5,
        brief: "",
        family: "express-bonus-yukon",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 29,
        optimalCells: 20,
        optimalSwitchCells: 9,
        wrenches: 10,
        puzzleString: "hhGcaC3OsoOsoOso7GcbG03GcbG03GcaC3OahOahOah"
      }
    ]
  },
  {
    id: "express-bonus-northwest-territories",
    title: "Bonus: Northwest Territories",
    playable: true,
    levels: [
      {
        id: "std-downUnder",
        title: "Down Under",
        number: 1,
        brief: "",
        family: "express-bonus-northwest-territories",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 31,
        optimalCells: 20,
        optimalSwitchCells: 11,
        wrenches: 10,
        puzzleString: "hh05OaaOaJOaoOaCOah9GeahGeaCGeaoGeaJGeaa0"
      },
      {
        id: "std-snowracer",
        title: "Snowracer",
        number: 2,
        brief: "",
        family: "express-bonus-northwest-territories",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 29,
        optimalCells: 24,
        optimalSwitchCells: 5,
        wrenches: 5,
        puzzleString: "hh6Giaa2R3Giah3RR1Giao1R3R1Ojo1RR3Ojh3R2Oja"
      },
      {
        id: "std-rightOfPassage",
        title: "Right of Passage",
        number: 3,
        brief: "",
        family: "express-bonus-northwest-territories",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 28,
        optimalCells: 19,
        optimalSwitchCells: 9,
        wrenches: 9,
        puzzleString: "hh1OsoRGebHROso01OaC03Osh03Oaa"
      },
      {
        id: "std-lamport",
        title: "Lamport",
        number: 4,
        brief: "",
        family: "express-bonus-northwest-territories",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 26,
        optimalCells: 20,
        optimalSwitchCells: 6,
        wrenches: 10,
        puzzleString: "hhGeaCOsh1Osh1OshGeaC2R1R0R1R1R0R1R2GbaCOao1Oao1OaoGbaC"
      },
      {
        id: "std-midland",
        title: "Midland",
        number: 5,
        brief: "",
        family: "express-bonus-northwest-territories",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 29,
        optimalCells: 17,
        optimalSwitchCells: 12,
        wrenches: 10,
        puzzleString: "hh2GeahGeahGeah9Oja5OBaOja2Pbc2OBaOja5OBa9GbahGbahGbah"
      }
    ]
  },
  {
    id: "express-bonus-nunavut",
    title: "Bonus: Nunavut",
    playable: true,
    levels: [
      {
        id: "std-entanglement",
        title: "Entanglement",
        number: 1,
        brief: "",
        family: "express-bonus-nunavut",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 27,
        optimalCells: 20,
        optimalSwitchCells: 7,
        wrenches: 11,
        puzzleString: "hhGeaCRRGeavRROvOO001Pco7Pbo7Paw"
      },
      {
        id: "std-dufferinGate",
        title: "Dufferin Gate",
        number: 2,
        brief: "",
        family: "express-bonus-nunavut",
        width: 7,
        height: 7,
        railLimit: 44,
        optimalRails: 22,
        optimalCells: 17,
        optimalSwitchCells: 5,
        wrenches: 10,
        puzzleString: "hhGcao2Pbw2Giah3Pbw6Pbw3Omaa2Pcw6Pbw6Pbw3Gcah2Pbw2Giao"
      },
      {
        id: "std-jumpingJoy",
        title: "Jumping Joy",
        number: 3,
        brief: "",
        family: "express-bonus-nunavut",
        width: 7,
        height: 7,
        railLimit: 48,
        optimalRails: 24,
        optimalCells: 18,
        optimalSwitchCells: 6,
        wrenches: 8,
        puzzleString: "hh3Gkah02OBo1Ojo4RPboR4OBo1Ojo02GkaC"
      },
      {
        id: "std-sidewinder",
        title: "Sidewinder",
        number: 4,
        brief: "",
        family: "express-bonus-nunavut",
        width: 7,
        height: 7,
        railLimit: 49,
        optimalRails: 37,
        optimalCells: 27,
        optimalSwitchCells: 10,
        wrenches: 10,
        puzzleString: "hh9RRR2Oaa2R2Gbah3Pbr3Oaa2Pab2Gbah3R3Oaa2R2Gbah"
      }
    ]
  }
];
